#!/usr/bin/env ruby

# Sample Pushfile that just does math
# See examples folder for more examples!

# first step is to require pushpop
require 'pushpop'

# now create any number of jobs with any number of steps

# this job run every second
# it will add 20 to 10 and return 30
job 'Simple Math' do
  every 1.seconds
  step do 10 end
  step do |response|
    20 + response
  end
  step do |response|
    puts 'Hello new Pushpop user, let\'s do a math!'
    puts "10 + 20 = #{response}"
  end
end
