#!/usr/bin/env ruby

require 'pushover'

job 'count total votes' do

  every 10.seconds

  keen do
    event_collection 'votes'
    analysis_type 'count'
    group_by 'character'
    timeframe 'last_7_days'
    interval 'daily'
  end

  step do |response|
    Pushover.logger.info(response)
  end

end
