#!/usr/bin/env ruby

require 'pushover'
require 'plugins/keen'

job 'count total votes' do

  every 10.seconds

  step 'query', 'keen' do
    event_collection 'votes'
    analysis_type 'count'
  end

  step 'log' do |responses|
    Pushover.logger.info(responses.first)
  end

end
