#!/usr/bin/env ruby

require 'pushover'

job do

  every 24.hours

  keen do
    event_collection 'pageviews'
    analysis_type 'count'
    timeframe 'last_24_hours'
  end

  sendgrid do |response|
    to 'josh@keen.io'
    from 'pushover@keen.io'
    subject "There were #{response} Pageviews Today!"
    body 'More blogging, yo!'
  end

  twilio do |_, step_responses|
    to '+17735405264'
    body "There were #{step_responses['keen']} Pageviews Today!"
  end

end
